global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'setpoint-operator'
    static_configs:
      - targets: ['setpoint-operator-metrics:8080']
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 3s
