apiVersion: v1
kind: ServiceAccount
metadata:
  name: setpoint-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: setpoint-operator
rules:
  - apiGroups:
      - setpoint.io
    resources:
      - industrialplcs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - setpoint.io
    resources:
      - industrialplcs/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - setpoint.io
    resources:
      - industrialplcs/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: setpoint-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: setpoint-operator
subjects:
  - kind: ServiceAccount
    name: setpoint-operator
    namespace: default
